-- LeakLens — Supabase schema (run in Supabase Dashboard → SQL Editor → New query)
-- Matches backend/src/services/* exactly (column names are snake_case there).

-- ============================================================
-- 1. Raw procurement transactions (loaded via CSV upload)
-- ============================================================
create table if not exists procurement_transactions (
    id            bigint generated by default as identity primary key,
    transaction_id text     not null unique,
    date          date      not null,
    product       text      not null,
    category      text      not null,
    supplier      text      not null,
    quantity      integer   not null check (quantity > 0),
    unit_price    numeric   not null check (unit_price >= 0),
    total_amount  numeric   not null check (total_amount >= 0),
    created_at    timestamptz not null default now()
);

-- ============================================================
-- 2. Detection-engine findings (written after each upload)
--    NOTE: no unique constraint on transaction_id on purpose —
--    one transaction can have multiple findings of different types.
-- ============================================================
create table if not exists leakage_results (
    id               bigint generated by default as identity primary key,
    transaction_id   text    not null,
    product          text    not null,
    supplier         text    not null,
    quantity         integer not null,
    actual_price     numeric,
    benchmark_price  numeric,
    potential_leakage numeric not null default 0,
    severity         text check (severity in ('HIGH', 'MEDIUM', 'LOW')),
    detection_type   text,
    reason           text,
    created_at       timestamptz not null default now(),
    constraint leakage_results_tx_fk
        foreign key (transaction_id)
        references procurement_transactions (transaction_id)
        on delete cascade
);

create index if not exists idx_leakage_tx on leakage_results (transaction_id);
create index if not exists idx_leakage_severity on leakage_results (severity);
create index if not exists idx_transactions_date on procurement_transactions (date);

-- ============================================================
-- 3. Row Level Security
--    The backend connects with the service_role key (SUPABASE_KEY),
--    which bypasses RLS — so no policies are needed and the tables
--    stay locked to anon/public access.
-- ============================================================
alter table procurement_transactions enable row level security;
alter table leakage_results enable row level security;
